/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfata;

import agenda.telefonica.Abonat;
import agenda.telefonica.NrFix;
import agenda.telefonica.NrMobil;
import agenda.telefonica.NrTel;
import static bazadedate.Conectare.verifyConnection;
import bazadedate.Interogari;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stan
 */
public class AdaugareAbonat extends javax.swing.JFrame {

    
    private final CarteDeTelefon carteDeTelefon;
    //private List<Abonat> lista_abonati;  
    
    /**
     * Creates new form AdaugareAbonat
     */
    public AdaugareAbonat() {
        initComponents();
        carteDeTelefon = new CarteDeTelefon();
    }
    
    public AdaugareAbonat(CarteDeTelefon carteDeTelefon){
        this.carteDeTelefon = carteDeTelefon;
    }
    
    protected CarteDeTelefon getCarteDeTelefon(){
        return carteDeTelefon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interfataAdaugare = new javax.swing.JPanel();
        tNume = new javax.swing.JTextField();
        bAdaugare = new javax.swing.JButton();
        bIesire = new javax.swing.JButton();
        tPrenume = new javax.swing.JTextField();
        tCNP = new javax.swing.JTextField();
        tNumarMobil = new javax.swing.JTextField();
        lNume = new javax.swing.JLabel();
        lPrenume = new javax.swing.JLabel();
        lCNP = new javax.swing.JLabel();
        lTelefonMobil = new javax.swing.JLabel();
        bRefresh = new javax.swing.JButton();
        tNumarFix = new javax.swing.JTextField();
        lTelefonFix = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAdaugare.setText("Adaugare");
        bAdaugare.setToolTipText("");
        bAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugareActionPerformed(evt);
            }
        });

        bIesire.setText("Iesire");
        bIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIesireActionPerformed(evt);
            }
        });

        lNume.setText("Nume");

        lPrenume.setText("Prenume");

        lCNP.setText("CNP");

        lTelefonMobil.setText("Telefon Mobil");

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        lTelefonFix.setText("Telefon Fix");

        javax.swing.GroupLayout interfataAdaugareLayout = new javax.swing.GroupLayout(interfataAdaugare);
        interfataAdaugare.setLayout(interfataAdaugareLayout);
        interfataAdaugareLayout.setHorizontalGroup(
            interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfataAdaugareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCNP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lTelefonMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lTelefonFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tNumarMobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(tNumarFix, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPrenume)
                    .addComponent(tCNP)
                    .addComponent(tNume))
                .addGap(18, 18, 18)
                .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bIesire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAdaugare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        interfataAdaugareLayout.setVerticalGroup(
            interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfataAdaugareLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNume)
                    .addComponent(tNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAdaugare)
                    .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lPrenume)))
                .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(interfataAdaugareLayout.createSequentialGroup()
                        .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNumarMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTelefonMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(interfataAdaugareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNumarFix)
                            .addComponent(lTelefonFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(interfataAdaugareLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bIesire)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lTelefonMobil.getAccessibleContext().setAccessibleName("Telefon mobil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(interfataAdaugare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interfataAdaugare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Butonul de adaugare abonat
    private void bAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugareActionPerformed
        try{
             Connection c = verifyConnection();
             PreparedStatement pst = c.prepareStatement(Interogari.queryAdaugare());
             
             Abonat abonat = new Abonat(tNume.getText(), tPrenume.getText(), tCNP.getText());
             NrMobil mobil = new NrMobil(tNumarMobil.getText());
             NrFix fix = new NrFix(tNumarFix.getText());
             
             pst.setString(1, tNume.getText());
             pst.setString(2, tPrenume.getText());
             pst.setString(3, tCNP.getText());
             pst.setString(4, tNumarMobil.getText());
             pst.setString(5, tNumarFix.getText());
             
             if(fix.verificareNrTel(tNumarFix.getText()) && mobil.verificareNrTel(tNumarMobil.getText())){
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Datele au fost inserate cu succes!");  
                 getCarteDeTelefon().refreshTabela();
                 getCarteDeTelefon().afiseaza_tabela(getCarteDeTelefon().extrageDinBazadeDate()); 
                 //getCarteDeTelefon().getTabela()
             }else{
                 JOptionPane.showMessageDialog(null, "Datele nu au fost inserate.");
             }            
        }
        catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }   
        catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(
                   this,
                    e.getMessage(),
                    "EROARE",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bAdaugareActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        tNume.setText("");
        tPrenume.setText("");
        tCNP.setText("");
        tNumarMobil.setText("");
        tNumarFix.setText("");
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIesireActionPerformed
        setVisible(false);
        //lista_abonati = getCarteDeTelefon().extrageDinBazadeDate();
        //getCarteDeTelefon().afiseaza_tabela(lista_abonati);
    }//GEN-LAST:event_bIesireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugareAbonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugareAbonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugareAbonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugareAbonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaugareAbonat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdaugare;
    private javax.swing.JButton bIesire;
    private javax.swing.JButton bRefresh;
    private javax.swing.JPanel interfataAdaugare;
    private javax.swing.JLabel lCNP;
    private javax.swing.JLabel lNume;
    private javax.swing.JLabel lPrenume;
    private javax.swing.JLabel lTelefonFix;
    private javax.swing.JLabel lTelefonMobil;
    private javax.swing.JTextField tCNP;
    private javax.swing.JTextField tNumarFix;
    private javax.swing.JTextField tNumarMobil;
    private javax.swing.JTextField tNume;
    private javax.swing.JTextField tPrenume;
    // End of variables declaration//GEN-END:variables

}
